# Generated by Django 5.2 on 2025-05-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subject',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile_images/no-avatar.jpg', upload_to='profile_images/'),
        ),
    ]
